apiVersion: v1
kind: Service
metadata:
  name: my-web-app-service
spec:
  type: NodePort
  selector:
    app: my-web-app
  ports:
    - name: http
      port: 80               # Service port inside Cluster
      targetPort: 8080       # Container port
      nodePort: 30080        # Port exposed on Worker Node (Choose 30000 - 32767)
